# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-31 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20180124_1327'),
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salthost',
            name='ip',
        ),
        migrations.AddField(
            model_name='salthost',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Server', verbose_name='\u4e3b\u673a'),
        ),
    ]
