# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-02 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_auto_20180201_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='salthost',
            name='key_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Accepted'), (2, 'Unaccepted'), (3, 'Deleted')], default=1, null=True, verbose_name='Key\u72b6\u6001'),
        ),
    ]
