# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-08 13:59
from __future__ import unicode_literals

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='phone',
        ),
        migrations.AddField(
            model_name='service',
            name='backstage',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u540e\u53f0\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bus_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u4e1a\u52a1\u8054\u7cfb\u4eba\u7535\u8bdd'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='business',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4e1a\u52a1\u8054\u7cfb\u4eba'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to=assets.models.contract_dir_path, verbose_name='\u5408\u540c'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tec_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='\u6280\u672f\u8054\u7cfb\u4eba\u7535\u8bdd'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='technical',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4e1a\u52a1\u8054\u7cfb\u4eba'),
        ),
    ]
