# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-12 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20171208_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.AlterField(
            model_name='requisition',
            name='payment',
            field=models.IntegerField(choices=[(1, '\u94f6\u884c\u652f\u4ed8'), (2, '\u652f\u4ed8\u5b9d\u652f\u4ed8')], default=1, verbose_name='\u652f\u4ed8\u65b9\u5f0f'),
        ),
    ]
