# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-15 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20171212_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='unit',
            field=models.IntegerField(choices=[(1, '\u4eba\u6c11\u5e01 CNY'), (2, '\u6e2f\u5e01 HKD'), (3, '\u7f8e\u91d1 USD')], default=1, verbose_name='\u91d1\u989d\u5355\u4f4d'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u670d\u52a1\u540d\u79f0'),
        ),
    ]
