# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-16 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20171215_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='approve_status',
            field=models.IntegerField(blank=True, choices=[(1, '\u5f85\u5ba1\u6838'), (2, '\u5df2\u901a\u8fc7'), (3, '\u672a\u901a\u8fc7')], default=1, null=True, verbose_name='\u5ba1\u6279\u72b6\u6001'),
        ),
    ]
