# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-18 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20180116_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='alive',
            field=models.BooleanField(default=False, verbose_name='\u5728\u7ebf\u72b6\u6001'),
        ),
    ]
