# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-19 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_server_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='node_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Minion ID'),
        ),
    ]
