# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-22 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_server_node_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverinfo',
            name='type',
        ),
        migrations.AddField(
            model_name='serverinfo',
            name='other_ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5176\u4ed6IP'),
        ),
    ]
