# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-01-24 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20180122_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u4ea7\u54c1\u578b\u53f7'),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='sn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5e8f\u5217\u53f7'),
        ),
    ]
