# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-28 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20180124_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='buy_date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='buy_date',
        ),
        migrations.AddField(
            model_name='server',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='service',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65e5\u671f'),
        ),
    ]
