# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-15 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=128, verbose_name='\u7528\u6237')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='\u64cd\u4f5c\u65f6\u95f4')),
                ('type', models.CharField(max_length=20, verbose_name='\u64cd\u4f5c\u7c7b\u578b')),
                ('action_ip', models.GenericIPAddressField(verbose_name='\u7528\u6237IP')),
                ('content', models.TextField(blank=True, max_length=100, null=True, verbose_name='\u5185\u5bb9')),
            ],
            options={
                'ordering': ['-operate_time'],
                'verbose_name': '\u64cd\u4f5c\u65e5\u5fd7',
                'verbose_name_plural': '\u64cd\u4f5c\u65e5\u5fd7\u5217\u8868',
            },
        ),
    ]
